### ISSUE TITLE
Add a report card to your RIM website.

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RIM#10]
Download [this file](https://github.com/Riverscapes/pyBRAT/blob/master/docs/Documentation/Status/Tool_ReportCard_3-1-00.md) and put it in your `docs\documentation\Status\` and edit accordingly...

**Comment by joewheaton** [comment]
@jtgilbert can you please set this up for one based on @kbartelt existing version? Then assign this to @nick4rivers to create a new version for the QRiS version that is coming in next few months: https://github.com/Riverscapes/QRiS/issues/48

**Comment by joewheaton** [comment]
Done with: https://rim.riverscapes.net/About/Status/Tool_ReportCard_0-1-00.html
@jtgilbert  please review and proofread.

**Comment by jtgilbert** [comment]
Cleaned up a few things in the report card.
