### ISSUE TITLE
Producing remaining fixes or bugs in `project.rs.xml` for RIM projects that need fixing for warehouse and RAVEPost here the problem with:

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RIM#12]
There are some known outstanding bugs in `project.rs.xml` that need fixing for both RIM and warehouse.

**Comment by kbartelt** [comment]
@jtgilbert at one point I manually edited the project.rs.xml files for each of the 20 projects in [this folder](https://usu.box.com/s/iwywy40hu9jzbsmdlaaf9eeiu0ogwaxe). I thought these were fixed and good to go, however, when I load a project into RAVE there are some summary comparison files that aren't appearing in the RAVE project explorer. Can you please verify if this is just an issue with the business logic or if there is still an issue with the project xml file? [Here is a video](https://youtu.be/2B2uaoggpvs) showing the problem.

I can do the manual edit for the remaining projects once we can confirm that the project xml is OK as it is in this folder and will make a video documenting this project because any project xml files will have the same issues (I wasn't able to fix this in the code).

**Comment by jtgilbert** [comment]
@kbartelt Thanks, it was just a little fix needed in the business logic, the edited project xmls are good.

**Comment by joewheaton** [comment]
Thanks @jtgilbert and @kbartelt for sorting this out. @jtgilbert can you confirm these are now handled correctly in ArcRAVE and QRAVE (I know symbology will be wrong in QRAVE until #14 is complete) but the projects should load right? If not, please post issues and we'll decide where to put them to fix.

**Comment by jtgilbert** [comment]
@joewheaton it works in Arc but projects don't load in Q, I posted an issue in the QRAVE repo.

**Comment by Jdgilby** [comment]
@joewheaton @jtgilbert @kbartelt I went through every site and all of them open in QRAVE, but there are some issues. Everything seems to load in sites within HUCS 1008002 and 16010203 aside from spawn_a and temple_a. Those two projects will open but the way it loads is screwed up. Every site outside of those HUCs open but none of inundation metrics get loaded in.

**Comment by CHafen** [comment]
@kbartelt I don't have access to the Box folder that has these projects in it. Is there a way you could grant me access to these projects?

**Comment by kbartelt** [comment]
@CHafen I just added you as an editor to the folder using your anabranch email address. Let me know if this didn't work.. I have fixed the project xmls for HUCs 16010203 and 10080002 but still need to fix the other HUCs. I will fix these tonight or tomorrow evening and will post here once completed. I just checked the project xmls for spawn_a and temple_a and I did update these and so I'm not sure what is going wrong with these two sites.

**Comment by kbartelt** [comment]
@Jdgilby @CHafen I went in and fixed all of the project xmls. Hopefully these all work in RAVE now.

**Comment by Jdgilby** [comment]
@kbartelt They all look good, thanks. The issue with spawn_a and temple_a was just a backwards project name and type in the xml. Also did you see the issue I commented on about some sites imagery not being georeferenced. That's the last problem I'm finding.

**Comment by CHafen** [comment]
When I open projects in Arc they initially seem to open just fine. But when I try to add all layers to map I get an error (see image). I think this is a problem with loading the imagery. I can't get the imagery in Arc, but it works just fine in Q for me. After the error shows up it doesn't load the inputs. I can go back in a load just the context, but not all the inputs.
![Inundation_error](https://user-images.githubusercontent.com/39837888/152050212-fdb87e2d-79c2-4860-8350-b5292c8ee377.png)

**Comment by Jdgilby** [comment]
@CHafen I wonder if it has something to do with the imagery being a png. The projects you got off of box still had them as pngs. I have changed them to tiffs and updated the project xmls that had problems. I can send you one to try out. I haven't uploaded the fixed projects yet.

**Comment by CHafen** [comment]
Thanks @Jdgilby why don't you go ahead and send me one and I can see if that works.

**Comment by Jdgilby** [comment]
murderers_a.zip
<https://drive.google.com/file/d/1X1TOuyYmumgSAXl-Z72Dhj0yN4CKd9mM/view?usp=drive_web>

**Comment by CHafen** [comment]
Thanks @Jdgilby looks like it works with the updated project.

**Comment by Jdgilby** [comment]
@CHafen Cool, Jordan is working on getting all the projects to the warehouse.
