### ISSUE TITLE
Fix or convert basemaps that are pngs that don't work (e.g. Google Earth)

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RIM#13]
@kbartelt will explain problem. I think easy fix is just to manually export the *.png to *.tiff geotiffs and make it work for her RIM projects.

**Comment by joewheaton** [comment]
@jtgilbert feel free to assign to Josh or Chalese once you have fix or solution.

**Comment by Jdgilby** [comment]
@kbartelt I got most of this sorted out however, in every site in the 17040101 HUC the imagery files aren't georeferenced. As well the big_wood_b site in HUC 17040219.

**Comment by joewheaton** [comment]
@Jdgilby I think you said you fixed this the other day? Re-Open and update status if I am arong.
