### ISSUE TITLE
Create a release of current RIM

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RIM#16]
@jtgilbert we need to as part of #1 get a release of @kbartelt code posted here. Lets zip up the deployable part, and make a release (we'll call it 1.0) and then record a video of how to deploy and apply it that we add in documentation.

Then we'll work on RIM 2.0 in QRiS with @nick4rivers.

**Comment by jtgilbert** [comment]
@joewheaton I think I need to be made co-owner of the repo to draft releases.

**Comment by kbartelt** [comment]
@jtgilbert I just made you an admit for this repo (I didn't see an owner option). Let me know if that didn't work or if you still don't have the necessary access for edits, releases, etc.

**Comment by jtgilbert** [comment]
Yep that worked, thanks @kbartelt

**Comment by jtgilbert** [comment]
@joewheaton to create a functional release from the scripts as is would take a bit of cleaning up. Right now it doesn't produce project.rs.xml files automatically in the right format to work with the business logic in RAVE. There area also a few missing files required by imports, unused import statements etc. Cashe mentioned that Tyler forked the repo and developed a Python toolbox using these scripts. I haven't tested it but what would you suggest is the best path for a 1.0 release?

**Comment by kbartelt** [comment]
@jtgilbert I think Tyler's version fixed the XML issue and cleaned up at least some of my extraneous/ messy code and helped with a few things I had wanted to change in the code but didn't know how to. I meant to merge his branch with the master to keep the improvements he made but never actually did. That branch is definitely the one to use- sorry I forgot to mention this sooner.

**Comment by jtgilbert** [comment]
@kbartelt Awesome, good to know!
