### ISSUE TITLE
Get rid of all hard-coded path dependencies and move to functions

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RIM#2]
As we discussed @kbartelt, please make changes to your code so that these are function calls and that no hard paths are coded in your code.

**Comment by philipbaileynar** [comment]
@kbartelt I just recorded a video on how to do this:

https://riverscapes.xyz/Tools/Technical_Reference/Documentation_Standards/Source_Code/#source-code-check-list

**Comment by joewheaton** [comment]
Thanks @philipbaileynar! Really helpful!

**Comment by kbartelt** [comment]
thank you @philipbaileynar, I appreciate the help.
