### ISSUE TITLE
method for pulling riverscape context layers by HUC id

### ISSUE THREAD

**Issue by kbartelt** [Riverscapes/RIM#7]
Hi @philipbaileynar 

I'm looking for a way to automatically or most efficiently download input data (DEMs and hillshades) into a desired project folder using the site's HUC code. I would also be interested in pulling other Riverscapes tool outputs (BRAT and VBET) if this were possible.

@joewheaton mentioned a Riverscapes Context script that does this from the USGS API. I briefly looked for this script in the pyBRAT repo but wasn't able to find it.

Do you have any advice for how to approach this? Thanks!

**Comment by philipbaileynar** [comment]
Is this a one-off request for one or just a few HUCs? Or is this a process that you foresee needing to run repeatedly on an as-needed basis going forward?

**Comment by kbartelt** [comment]
For my thesis it is a one-off request. It is for about 60 sites that fall under 15 different HUC8's

**Comment by philipbaileynar** [comment]
Karen can you put the list of eight digit HUCs on this issue please.

**Comment by kbartelt** [comment]
Here is the list:

[HUC8_list.txt](https://github.com/Riverscapes/inundation/files/4698713/HUC8_list.txt)

HUC8
10080002
10080003
10180006
16010101
16010202
16010203
16020102
16020304
16020308
17040218
17040219
17060201
17070201
17070203
17070204

**Comment by philipbaileynar** [comment]
@kbartelt do you have access to the riverscapes data warehouse? I'm providing links to those HUCs that have already been processed. Can you download one and confirm if it has the items that you need?

**Comment by kbartelt** [comment]
Thank you @philipbaileynar. I do not have access to the data warehouse.

**Comment by philipbaileynar** [comment]
I just created an account for you. Check your email for a link to reset your password before you can login. Let me know if you have any problems.

**Comment by kbartelt** [comment]
I downloaded one and it has what I need. Thank you once again for the help Philip!

**Comment by philipbaileynar** [comment]
@kbartelt I've run all the HUCs that are straightforward. Links above.

Those within the two digit 10 HUC are complicated because the USGS have an error in their metadata on Science Base. When our code searches for NHD datasets within `HUC_1008` no results are returned. I have reported the problem to the USGS and they responded that they are working to fix the problem. I don't know the turnaround time. We have a strategy for getting around this but it's manual and fiddly.

Hopefully the HUCs that I have run for you are enough to be getting on with, while we wait for the USGS to fix their data.

**Comment by joewheaton** [comment]
Philip, this above and beyond and hugely appreciated. Thank you so much.

**Comment by joewheaton** [comment]
@kbartelt even without the Big Horn (1008) of 10080002 (Little Wind) and 10008003 (Popo Agie), and the North Platte (1018) of 1018006 (Sweet Water), this is a remarkable coverage. The Upper & Lower Snake, Bear, Great Salt Lake Basin, Middle Columbia cover a nice cross section of mid-latitudes (38.7 to 47.6) spanning the eastern rockies, all the way to the east slope of the Cascades and really capturing the heart of the Intermountain West and the Rockies well. I'm thinking this simple context (of Riverscapes Context) combined with ecoregions is really helpful in contextualizing your thesis study design.  Can you make an updated study site map that shows the dots for your 60+ sites, the HUC 8's they are part of, these HUC 4's, a hillshade underneath, and Level 1 ecoregions?

![image](https://user-images.githubusercontent.com/9723905/83360861-c914b280-a341-11ea-8f9f-716beda782b7.png)

**Comment by kbartelt** [comment]
Thank you so much for these @philipbaileynar, I really appreciate it. @joewheaton I like that idea for an updated study site map and will make one as you described above.
